language: python
sudo: false
services:
- postgresql
env:
- DATABASE_URL='postgres://postgres:@localhost:5432/compshop_test' DJANGO_SETTINGS_MODULE='settings.test'
python:
- '3.6'
addons:
  postgresql: '9.4'
install:
- pip install -r requirements/local.txt
- pip install coveralls
before_script:
- psql -c 'create database compshop_test;' -U postgres
- python manage.py migrate --noinput
- python manage.py collectstatic --noinput
script:
- make test
after_success: coveralls
deploy:
  provider: heroku
  api_key:
    secure: mq2u0rW1KW5ZUsCV0LJvg6bAU3Q+0mBzV6VSKDzEoBheKMZxPyUdvKlGocbbBlcwWt4wFz013sVf4POZeaFL9G9d9mLSj9t0HAXDYs45GYsoit32vm/Mt5/kn5GIuhBROHJg/0j0valkZV55S0dDwleEg3N2YYAausLFyU5YkKvTMdgL1/EGQj28yDlZzx1w6zfWHaC03nIORreMVFkuTzrK4KRHSE0w9b7mdzCCc4CVR+vFgl/RCUppZQhFA1aPmnAPqx4gZmJWDUcZnDCognLCp6n/7dLnuobge/SiM5qM1gkXoUYI57X+32xqtVFiGF69zKw/xJT6j/AxE4CwnLJU2NUcr+2bvtGm7/33AcocS1tRXovi3MbA65gp7qKaiHURmXxVD0BhDf0NM3Qz2VTy+AzIpmZ/jP615jA8daijMZnlZuDtv8HRGUdPPzIp5LNx5vqD6Ly7amsT32TqJ2Ws3y+OCyeHsW8YPaFRoUUivDR38ERtMPp9wv7fMfQhZjekU9Di1jdBBDqkyIhKYIgjR5xaQkq69GiOBPoAi7d9tIIS/LA1e4BHcsilTwU3uvOAVnm324vHsyqkMRiLH64Lr4Fdt6mYImkj2SDnR5j3K6lJtq4wEP/Fx9COasNu9ariFoksFp3pcy2R6ThN2ma0r20qNXFojfpLceKJ9QM=
  app: comptronics
  on:
    repo: kevgathuku/compshop
    branch: develop
  run: python manage.py migrate
