language: python
sudo: false
services:
- postgresql
env:
- DATABASE_URL='postgres://postgres:@localhost:5432/compshop_test' DJANGO_SETTINGS_MODULE='settings.test'
python:
- '3.6'
addons:
  postgresql: '9.4'
install:
- pip install -r requirements/local.txt
- pip install coveralls
before_script:
- psql -c 'create database compshop_test;' -U postgres
- python manage.py migrate --noinput
- python manage.py collectstatic --noinput
script:
- make test
after_success: coveralls
deploy:
  provider: heroku
  api_key:
    secure: Sft6mwV52lRfW8udjgvd9YMdPr0K3Wy7T7CzCUNRvjBrFTVMGZ1WsKNzzDnw+X/rfgpQYSpxBF83uLf1TdZf+L76n/ekW8gLmBar7gJivOUIbbHWjfIsp6WD+kzASJpBkYYVbzeZsy1VjFEUVvxuYwecWqUslJGL/xDaDWBD/ESX2GyEn33HFMP/9veEw0R0l3YergApwireKKHYzP9cIe3RSXvSTlC/1JY6iao12roqteH8Er//w+li194kgfQfnEW15u/H2BWEFq6bqhp33wctn/gIRu7XM71ZW+zSG6ZVIkDv42u93butBriyRVszQO6jG4IttISMYvlttymmo8NugO5P//aXJHV6C4goF9qIcQkoskqJcMOJuv0TwMYB1cmVQreponKNytTuxmIh9jEw0DfUbrgSyFQi3hReKNF6hjdp1fJWsaxRXFtDFcMuTQPT90uGkW6q8yInRvA1iQcScjk7LoskXPipp/wj+oY82sybouh4aNrSWawfxUEJWThHlFX8W2ErI7YlLbs2cbvSw+R7OrmiFJjnemPNl3RLQRQ/Mj6f9wMnsyql1MXtSagn45c+XCnMS337qKPFZchRxrabLGvj0NUTuxQRGMtudXQda5Y5dNDy14sm6ZQHtKy36httOqC+K6zeIOgG55cRvLfRJTkpm2L9N9cw9IU=
  app: comptronics
  on:
    repo: kevgathuku/compshop
    branch: develop
  run: python manage.py migrate
