language: python
services:
- postgresql
env:
- DATABASE_URL='postgres://postgres:@localhost:5432/compshop_test' DJANGO_SETTINGS_MODULE='settings.test'
python:
- '3.4'
addons:
  postgresql: '9.4'
install:
- pip install -r requirements/testing.txt
- pip install coveralls
before_script:
- psql -c 'create database compshop_test;' -U postgres
- python manage.py migrate --noinput
- python manage.py collectstatic --noinput
script:
- make test
after_success: coveralls
deploy:
  provider: heroku
  api_key:
    secure: tmC9Ic3GZvrpWymjdTklxuawjMfhGNFpnisgeyt85L0jF7DcqE7Qwkihq1E3282LCWjFVtH//PuUDRHjumavyTg8sD6W3had/xPZH7Yoq5TbbAQxYGnptTImIJelWEC/bMMYPViNotbIUbe2h04O5rqCjJSOa/c56JtotmBqcfI=
  app: comptronics
  on:
    repo: kevgathuku/compshop
    branch: develop
  run: "python manage.py migrate"
